#!/bin/bash

echo
echo Start checking...
echo

g++ generator.cpp -o generator
g++ task1.cpp -o task1
g++ task2.cpp -o task2

while true
do
	./generator
	./task1
	./task2

	diff -q -Z ans1.out ans2.out > /dev/null
	if [ $? == 1 ]
	then
		echo DIFF
		break;
	else
		echo -n .
	fi
done

echo
echo DONE

echo

